name: Build and Release lightfm-mirror

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
  workflow_dispatch:

env:
  # Configure cibuildwheel 
  CIBW_SKIP: "pp* *-musllinux_i686"  # Skip PyPy and 32-bit musllinux
  CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"  # Python 3.9-3.12
  # Test installation works
  CIBW_TEST_COMMAND: "python -c 'import lightfm; print(lightfm.__version__)'"
  # Skip testing on emulated architectures for speed
  CIBW_TEST_SKIP: "*-*linux_{aarch64,ppc64le,s390x} *-musllinux*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.0.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload lightfm-mirror to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    # Only run on releases
    if: github.event_name == 'release' && github.event.action == 'published'
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Publish lightfm-mirror to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1